basic.forever(function () {
    led.plot(4, 4)
    basic.pause(400)
    led.plot(4, 3)
    basic.pause(300)
    led.plot(4, 2)
    basic.pause(300)
    led.plot(4, 1)
    basic.pause(300)
    led.plot(4, 0)
    basic.pause(400)
    led.unplot(4, 0)
    basic.pause(300)
    led.unplot(4, 1)
    basic.pause(300)
    led.unplot(4, 2)
    basic.pause(300)
    led.unplot(4, 3)
    basic.pause(400)
    basic.clearScreen()
    led.plot(4, 3)
    basic.pause(300)
    basic.clearScreen()
    led.plot(4, 2)
    basic.pause(300)
    basic.clearScreen()
    led.plot(4, 1)
    basic.pause(300)
    basic.clearScreen()
    led.plot(4, 0)
    basic.pause(400)
    basic.clearScreen()
    led.plot(4, 1)
    basic.pause(300)
    basic.clearScreen()
    led.plot(4, 2)
    basic.pause(300)
    basic.clearScreen()
    led.plot(4, 3)
    basic.pause(300)
    basic.clearScreen()
    led.plot(4, 4)
})
